### ISSUE TITLE
Reorganize external database access

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/autoreporting#88]
Important to #79 and #87 
Reorganize external database access so that
- Dataresources can be defined in main.py and compare.py without duplication of code
- Dataresources are under one place, and adding new ones does not create changes in the objects that query dataresources (e.g. compare.py)
- Threading etc happens in the dataresource, so resources that benefit from it receive the advantages, but resources that are by design single-threaded (e.g. access to a single dataframe/file) are not hindered by it

## TODO:
- [x] Place all dataresources under one place (datafactory or similar)
- [x] Move multithreading to the dataresources that can use it
- [x] Unify the calling of dataresources so that the interface does not change depending on what or how many dataresources are in use
- [ ] OPTIONAL: make calling of dataresources asynchronous, i.e. make it possible for multiple dataresources to fetch the data simultaneously. Benchmark whether this makes sense
